### ISSUE TITLE
Document need more detail

### ISSUE THREAD

**Issue by yxshawn** [fog/fog-aliyun#13]
Since the document in Aliyun didn't define the *\* aliyun_oss_endpoint*\*  , *\* aliyun_oss_location*\* and \* aliyun_oss_bucket\* like this gem does. 

It took me sometime to figure it out. Give an example might help more people like me.

```
aliyun:
    provider:                aliyun
    aliyun_accesskey_id:     <YOUR KEY>
    aliyun_accesskey_secret: <YOUR SECRET>
    aliyun_oss_endpoint:     http://oss-cn-beijing.aliyuncs.com
    aliyun_oss_location:     oss-cn-beijing
    aliyun_oss_bucket:       mybucket 
```

Especially:
1. aliyun_oss_endpoint **MUST** contain "http://" and **MUST NOT** contain bucket name. Aliyun defines my endpoint as  **mybucket.oss-cn-beijing.aliyuncs.com** instead of **http://oss-cn-beijing.aliyuncs.com**
2. aliyun_oss_location can be found in the part from your endpoint.

**Comment by plribeiro3000** [comment]
@yxshawn Would you be able/want to open a PR adding it?

**Comment by dengqinsi** [comment]
fixed by https://github.com/fog/fog-aliyun/pull/19
