### ISSUE TITLE
fog-aliyun is not compatible with Ruby 3.X

### ISSUE THREAD

**Issue by johha** [fog/fog-aliyun#156]
With Ruby 3.x this gem cannot be used anymore due to the following error:
```
undefined method `encode' for URI:Module
```

The `encode` method was removed with Ruby 3: https://docs.knapsackpro.com/2020/uri-escape-is-obsolete-percent-encoding-your-query-string

To reproduce the issue run the unit/integration test with ruby 3.x. This can be done for example by changing the version in `.ruby-version` to e.g. `3.0.4`.

Open questions:
- Does `aliyun-sdk` needs to be updated and test as well? Looks like last commit is ~2 years old.

**Comment by stephanme** [comment]
Thanks for merging #158 and releasing it as [v0.4.0](https://github.com/fog/fog-aliyun/releases/tag/v0.4.0)
