### ISSUE TITLE
Incomplete error status code handling

### ISSUE THREAD

**Issue by ninja-at-work** [fog/fog-aliyun#52]
Hi,

The 404 check in https://github.com/fog/fog-aliyun/blob/bb94a832bd6e0954443e92f16f1dcbddf89d94d8/lib/fog/aliyun/models/storage/files.rb#L159 is not sufficient, as it doesn't handle any other error status (like 403 or 500).

This code should be updated to introduce better error status handling.
In addition, it makes sense to introduce status check guard logic also to other places where the interaction with OSS API is made.
For example, it can make sense to additionally handle the errors in these functions:
https://github.com/fog/fog-aliyun/blob/master/lib/fog/aliyun/models/storage/files.rb#L18
https://github.com/fog/fog-aliyun/blob/master/lib/fog/aliyun/models/storage/files.rb#L60

Thanks

**Comment by xiaozhu36** [comment]
HI @ninja-at-work I have added more conditions in the PR #53 to fix this issue. But this PR may not match your point. Based on the [OSS docs ](https://www.alibabacloud.com/help/doc-detail/31965.htm) and the following reason, I think there is no need to check more error code(like 403, 500):
1. The method `HeadObject`, `GetObject` and `ListObject` won't return 500 and `HeadObject` also won't return 403. 
2. `GetObject` 403 error is `InvalidObjectState` not a `NotFound` error. 
3. `ListObject` 403 error is `AccessDenied` not a `NotFound` error. 
4. `GetObject` will return 404 and it has two cases. I have added another case in the #53

**Comment by ninja-at-work** [comment]
Hi @xiaozhu36 ,

According to the https://www.alibabacloud.com/help/doc-detail/32005.htm the OSS API responds with specific error code according reflecting condition caused the error.

Also in this (https://www.alibabacloud.com/help/doc-detail/31965.htm) document states the following:

> If the bucket to be accessed does not exist, a 404 Not Found error is returned with the error code NoSuchBucket.
> If you have no permission to access the bucket, OSS returns a 403 Forbidden error with the error code AccessDenied.

**Comment by xiaozhu36** [comment]
Hi @ninja-at-work Thanks for your reply and advise. I have reviewed the codes again and the results as follows:
1. head_object
 This method is used in three places:
   * https://github.com/fog/fog-aliyun/blob/master/lib/fog/aliyun/models/storage/file.rb#L177
      I have added a if block to avoid 404 error. See #54 .
   * https://github.com/fog/fog-aliyun/blob/master/lib/fog/aliyun/models/storage/directories.rb#L30
      This place has handled the data status 200.
    * https://github.com/fog/fog-aliyun/blob/master/lib/fog/aliyun/models/storage/files.rb#L158
       This place has handled the data status 404.

2. get_object
    This method is used in three places:
      * https://github.com/fog/fog-aliyun/blob/master/lib/fog/aliyun/models/storage/files.rb#L68
         This place has handled the notfound error
      * https://github.com/fog/fog-aliyun/blob/master/lib/fog/aliyun/models/storage/files.rb#L87
         I have added a begin block to handle notfound error. See #55.

Please let me know if you have more ideas for the #54 and #55?

**Comment by ninja-at-work** [comment]
Hi @xiaozhu36, the code changes (PRs #54 and #55) and the areas you identified are good.
I'd strongly recommend adding unit tests in all these areas to verify this logic.

**Comment by xiaozhu36** [comment]
Hi @ninja-at-work The PR #54 and #55 have been tested in my local CF. If you does not have more ideas, I will cut a new release to support them.
Indeed, I have started to study ruby to make the fog-aliyun more stronger and  add unit tests for it.

**Comment by xiaozhu36** [comment]
Fixed by 0.3.17.
