### ISSUE TITLE
Enhance tests

### ISSUE THREAD

**Issue by ninja-at-work** [fog/fog-aliyun#67]
# Motivation

This document proposes enhancements to be done for integration/unit tests to increase fog-aliyun library code coverage and improve stability as far as more integration tests will run on automatic/nightly basis.

# Area to be covered

Currently, the primary targets of this document is to provide tests scenarios for storage and OSS buckets api area, as it's critical for CloudFoundry operations.

# Test environments

General recommendation is to run this test on automatic (when a new PR or commit enter into the repository) and on nightly basis to catch issues if some changes be at AliCloud OSS api level.

As regions available in China and Worldwide may differ from each other, it recommended to run integration test in China region (Shanghai) and in Europe (Frankfurt) to verify that the library behave equally regardless of region.

Extra options for test environments:
- Run tests with internal endpoint

| Region | Public Endpoint | Private Endpoint |
|-|-|-|
| Shanghai |  |  |
| Frankfurt |  |  |

Priority: HIGH

# Test scenarios

## Auth & Connectivity scenarios

1. Test that API can be accessed using valid credentials:
    - The goal of this test is to verify that connection to api is possible using valid credentials.
    - Expected result: OSS API should be accessible
    - Priority: High
1. (NEGATIVE TEST) Test that API cannot be accessed using incorrect credentials:
    - The goal of this test is to get error if connection to api is not possible due to invalid credentials.
    - Expected result: An error should be thrown with details.
    - Priority: Low
1. Test that API can be accessed if time zone is correct (valid signature computation)
    - The goal of this test is to validate that signature generated for requests is valid and acceptable by API.
    - Expected result: OSS API should be accessible
    - Priority: Low
1. (NEGATIVE TEST) Test that API can be accessed if time zone is NOT correct (invalid signature computation)
    - The goal of this test is to provide error details if signature wrongly generated (for example if timezone incorrect)
    - Expected result: An error should be throw with details.
    - Priority: Low
1. Test region is selected according to provider configuration
    - The goal of this test is to ensure that region provided in configuration is really used for connection.
    - Expected results: The requests should point to the provided region
    - Extra scenario: check default region is used if no region provided explicitly.
    - Priority: High

## Entity operations

1. Add tests for each type of entity that validates the following operations:

|Method | Description| Priority |
-- | -- | --
create | Accepts hash of attributes and creates object.Note: creation is a non-blocking call and you will be required to wait for a valid state before using resulting object. | High
save | Saves object.Note: not all objects support updating object. | High
destroy | Destroys object.Note: this is a non-blocking call and object deletion might not be instantaneous. | High
reload | Updates object with latest state from service. | Medium
attributes | Returns a hash containing the list of model attributes and values. | Medium
identity | Returns the identity of the object.Note: This might not always be equal to object.id. | Low

## Buckets scenarios

1. Test that it is possible to get single bucket
    - Get listing of single bucket
    - Expected result: Bucket should be found
    - Priority: Low
1. Test that it is possible to list all buckets
    - Get listing of all buckets
    - Expected result: Buckets should be found
    - Extra scenarios: List buckets using prefix, marker and maxKeys options.
    - Priority: Low
1. Test that it is possible to create a new bucket.
   - Create new bucket using api
   - Expected result: Bucket should be created
   - Priority: Low
1. Test that it is possible to destroy a bucket.
   - Destroy bucket using api
   - Expected result: Bucket should be deleted
   - Priority: Low
1. (NEGATIVE TEST) Test that error is thrown when trying to create already existing bucket
   - Create a new bucket using the same name as the already existing one. 
   - Expected result: On save it should throw exception.
   - Priority: Low
1. (NEGATIVE TEST) Test that error is thrown when trying to access non-existing bucket
   - Ask for non-existing bucket should fail with error.
   - Expected result: Not found error
   - Priority: Low
1. (NEGATIVE TEST) Test that error is thrown when trying to destroy non-existing bucket
   - Destroy for non-existing bucket should fail with error.
   - Expected result: Not found error
   - Priority: Low
1. (NEGATIVE TEST) Test that error is thrown when trying to access protected bucket from other account.
   - Ask for protected bucket should fail with error.
   - Expected result: Not found error / Access error?
   - Priority: Low

## Files & Directory scenarios

 1. Test get nested directories and files in nested directory
     - The goal of this test is to validate that files and directories can be queried if structure is nested.
     - Expected result: Nested list should be possible. 
     - Priority: Medium
 1. Test that it is possible to upload (write) a file
     - The goal of this test is to validate that file is persisted correctly 
     - Expected result: The file is created and the content equal to the uploaded file
     - Priority: High
1. Test that it is possible to upload (write) large file (multi part upload)
     - The goal of this test is to validate that file is persisted correctly 
     - Expected result: The file is created and the content equal to the uploaded file
     - Priority: High
1. Test that it is possible to get file details like `public_url`
    - The goal of this test is to test attributes of files
    - Expected result: The attribute should match to the expected value
    - Priority: Low
1. Test that it is possible to destroy a file/directory
    - The goal of this test is to check destroy functionality
    - Expected result: Should destroy the file/directory
    - Extra scenario: Destroy of non-empty directory should fail
    - Priority: High
1. Test file/directory listing using parameters such as `prefix`, `marker`, `delimeter` and etc...
    - The goal of this test is to check that response returned according to the provided parameters.
    - Expected result: Response should meet expectations
    - Priority: High
1. Test file copy operations
    - The goal of this test is to verify file copy operations.
    - Expected result: The copy of file should match to the original file
    - Priority: Low
1. Test getting bucket when directory exists named with the same name as a bucket.
    - The goal of this test is to check that fog receives a reference to directory and not to the bucket if 
directory name matches to the bucket name.
   - Expected result: The api should provide reference to the bucket (like in AWS).
   - Priotity: Low

**Comment by xiaozhu36** [comment]
Fixed.
