### ISSUE TITLE
Rubygems Metadata Update Request

### ISSUE THREAD

**Issue by JuanitoFatas** [fog/fog-aliyun#7]
Hi :wave: . I notice your Homepage metadata is:

```
https://github.com/fog/fog-aliyun.git
```

instead of

```
https://github.com/fog/fog-aliyun
```

Could you update at https://rubygems.org/gems/fog-aliyun/edit?

Thank you! :bow:

**Comment by plribeiro3000** [comment]
@geemus Can you take a stab at this please?
It should be really quick but i don't have access.

**Comment by geemus** [comment]
Looks like it has to be fixed in gemspec actually. I've made the change here: https://github.com/fog/fog-aliyun/commit/b4c6eabcb6cf3ddd270157c381176342d93c2fe2 (but presumably it won't appear until the next release).

@JuanitoFatas thanks for the heads up!

**Comment by dengqinsi** [comment]
@JuanitoFatas @plribeiro3000 @geemus  Thanks. 
I have fixed a bug and push a new gem package at version 0.1.0.
And I have tag v0.1.0.

**Comment by JuanitoFatas** [comment]
Wow thanks everyone!!! :beers:
