### ISSUE TITLE
HTTPS access to endpoint

### ISSUE THREAD

**Issue by ninja-at-work** [fog/fog-aliyun#70]
Hello,

The current fog-aliyun implementation has hardcoded "http" protocol for generating endpoint url (https://github.com/fog/fog-aliyun/search?q=http%3A%2F%2F&unscoped_q=http%3A%2F%2F).
This can be a security issue, as http protocol is not safe. 

Please provide a configuration to force HTTPs usage and generate endpoint with appropriate protocol based on this configuration.

**Comment by xiaozhu36** [comment]
Supported by release 0.3.11.
